In [60]:
import numpy as np
import torch

In [47]:
w=np.linspace(1,9,8).reshape(8,)

In [48]:
w=torch.from_numpy(w)

In [49]:
w

tensor([1.0000, 2.1429, 3.2857, 4.4286, 5.5714, 6.7143, 7.8571, 9.0000],
       dtype=torch.float64)

In [50]:
w.backward

<bound method Tensor.backward of tensor([1.0000, 2.1429, 3.2857, 4.4286, 5.5714, 6.7143, 7.8571, 9.0000],
       dtype=torch.float64)>

In [66]:
import torch.nn as nn
from torch.utils.data import TensorDataset,DataLoader

In [61]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [63]:
train_ds=TensorDataset(inputs,targets)

In [65]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [67]:
batch_size=5
train_dl=DataLoader(train_ds,batch_size,shuffle=True)

In [74]:
for xb ,yb in train_dl:
    print(xb)
    print(yb)
    

tensor([[ 91.,  87.,  65.],
        [ 73.,  66.,  44.],
        [ 87., 135.,  57.],
        [ 69.,  96.,  70.],
        [ 68.,  96.,  71.]])
tensor([[ 80., 102.],
        [ 57.,  69.],
        [118., 134.],
        [103., 119.],
        [104., 118.]])
tensor([[103.,  43.,  36.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 92.,  87.,  64.],
        [ 91.,  88.,  64.]])
tensor([[ 20.,  38.],
        [ 56.,  70.],
        [ 22.,  37.],
        [ 82., 100.],
        [ 81., 101.]])
tensor([[ 87., 134.,  58.],
        [ 68.,  97.,  70.],
        [ 74.,  66.,  43.],
        [101.,  44.,  37.],
        [ 88., 134.,  59.]])
tensor([[119., 133.],
        [102., 120.],
        [ 57.,  69.],
        [ 21.,  38.],
        [118., 132.]])


In [76]:
model=nn.Linear(3,2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.4857,  0.5043, -0.3985],
        [ 0.0364,  0.4945, -0.0454]], requires_grad=True)
Parameter containing:
tensor([-0.1015,  0.5126], requires_grad=True)


In [77]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.4857,  0.5043, -0.3985],
         [ 0.0364,  0.4945, -0.0454]], requires_grad=True),
 Parameter containing:
 tensor([-0.1015,  0.5126], requires_grad=True)]

In [79]:
preds=model(inputs)
preds

tensor([[-18.9090,  34.3437],
        [-25.4307,  44.4282],
        [  2.0988,  67.3003],
        [-42.7064,  23.8042],
        [-13.1015,  47.3110],
        [-19.8990,  33.8856],
        [-26.3335,  43.8883],
        [  1.2146,  67.2913],
        [-41.7164,  24.2623],
        [-13.0143,  47.2292],
        [-19.8117,  33.8038],
        [-26.4207,  43.9701],
        [  3.0015,  67.8402],
        [-42.7937,  23.8860],
        [-12.1115,  47.7690]], grad_fn=<AddmmBackward0>)

In [80]:
import torch.nn.functional as F

In [81]:
loss_func=F.mse_loss

In [83]:
loss=loss_func(preds,targets)
loss

tensor(6228.9380, grad_fn=<MseLossBackward0>)

In [86]:
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

In [87]:
def fit(num_epoch,model,loss_fn,opt,train_dl):
    #number of epochs
    for epoch in range(num_epoch):
        for xb,yb in train_dl:
            pred=model(xb)
            loss=loss_fn(pred,yb)
            loss.backward()
            opt.step()
            opt.zero_grad()
        if(epoch+1)%10==0:
            print('Epoch[{}/{}], loss:{:.4f}'.format(epoch+1,num_epoch,loss.item()))
    

In [90]:
fit(120,model,loss_func,opt,train_dl)

Epoch[10/120], loss:18.4070
Epoch[20/120], loss:32.6903
Epoch[30/120], loss:24.6396
Epoch[40/120], loss:18.8796
Epoch[50/120], loss:30.3645
Epoch[60/120], loss:17.9153
Epoch[70/120], loss:8.9092
Epoch[80/120], loss:30.5658
Epoch[90/120], loss:18.1126
Epoch[100/120], loss:24.7598
Epoch[110/120], loss:32.2356
Epoch[120/120], loss:27.9784
