In [7]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
import matplotlib.pyplot as plt
%matplotlib inline

In [39]:
dataset=pd.read_csv("Position_Salaries.csv")

In [51]:
x=dataset.iloc[:,1].values
y=dataset.iloc[:,-1].values
x=x.reshape(len(x),1)
y=y.reshape(len(y),1)

In [52]:
tree=DecisionTreeRegressor(random_state=0)
tree.fit(x,y)

DecisionTreeRegressor(random_state=0)

In [53]:
tree.predict(x)

array([  45000.,   50000.,   60000.,   80000.,  110000.,  150000.,
        200000.,  300000.,  500000., 1000000.])

In [54]:
y

array([[  45000],
       [  50000],
       [  60000],
       [  80000],
       [ 110000],
       [ 150000],
       [ 200000],
       [ 300000],
       [ 500000],
       [1000000]], dtype=int64)

In [36]:
tree.predict([[5.6]])

array([150000.])